name: PHP CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-version: [7.3, 7.4, 8.0, 8.1, 8.2]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl

      - name: Install Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tool-cache: true
          run: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"

      - name: Install dependencies
        run: composer install

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit

      - name: Commit and push
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: EndBug/add-and-commit@v7
        with:
          author_name: LIUJIAN
          author_email: your-email@example.com
          message: "Automated commit by GitHub Actions"
          force: true
          push: true
