name: Split

on:
  push:
    branches: [ master ]
jobs:
  split:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run
        run: |
          git config pull.rebase true
          git config --global user.email "onanying@126.com"
          git config --global user.name "liujian"
          chmod 777 shell/*
          ./shell/split-linux.sh
