name: Split

on:
  push:
    branches: [ master ]
jobs:
  split:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run
        run: |
          git config --global user.email "onanying@126.com"
          git config --global user.name "liujian"
          chmod 777 shell/*
          ./shell/split-linux.sh
