name: Split

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Run
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        git config pull.rebase true
        git config --global user.email "onanying@126.com"
        git config --global user.name "liujian"
        bash shell/split-linux.sh
