name: Split

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Split
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          sh shell/split-linux.sh
